# Copyright (C) 2006-2014 David Sugar, Tycho Softworks.
# Copyright (C) 2015-2017 Cherokees of Idaho.
#
# This is a default template for a post-install scriptlet.
# Uncomment only required functions and remove any functions
# you don't need (and this header).

## arg 1:  the new package version
post_install() {
	chmod +s /usr/bin/sippasswd
	groupadd -r sipwitch
}

post_upgrade() {
	chmod +s /usr/bin/sippasswd
}

## arg 1:  the old package version
pre_remove() {
	groupdel sipwitch
}

