.\" sipquery - register and report sip contact details
.\" Copyright (c) 2009 David Sugar <dyfet@gnutelephony.org>
.\"
.\" This manual page is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc.,59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
.\"
.\" This manual page is written especially for Debian GNU/Linux.
.\"
.TH sipquery "1" "December 2009" "GNU SIP Witch" "GNU Telephony"
.SH NAME
sipquery \- register and report sip contact details
.SH SYNOPSIS
.B sipquery
.B -forward \fIipaddr\fR
.B -port \fInumber\fR
.B -proxy \fIsip:host[:port]\fR
.B -server \fIsip:host[:port]\fR
.B -timeout \fIseconds\fR
.B -verbose
.I userid[@server[:port]]
.SH DESCRIPTION
This is a tool that uses the registration process to query the sip contact
uri for a registered user agent.  This may even be considered a demonstration
of a security flaw in the standard SIP server model.  Basically, an
un-authenticated registration request is sent to the server, and the contact
uri is read to standard out from the server reply message.
.SH OPTIONS
.TP
.B -forward
Sets the "public appearing" IP address for testing behind NAT.
.TP
.B -port 
Sets the sip port number, in case the default port (5060) is in use already.
.TP 
.B -proxy 
Use a specified outbound proxy uri to get to the server being queried.
.TP
.B -server 
Specify server uri to query unless offered as part of userid.
.TP
.B -timeout 
Time to wait for query response.
.SH AUTHOR
.B sipquery
was written by David Sugar <dyfet@gnutelephony.org>.
.SH "REPORTING BUGS"
Report bugs to sipwitch-devel@gnu.org.
.SH COPYRIGHT
Copyright \(co 2009 David Sugar, Tycho Softworks.
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.

