.\" siprealm - show or set authentication realm of sipwitch services.
.\" Copyright (c) 2010 David Sugar <dyfet@gnutelephony.org>
.\"
.\" This manual page is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc.,59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
.\"
.\" This manual page is written especially for Debian GNU/Linux.
.\"
.TH siprealm "1" "January 2010" "GNU SIP Witch" "GNU Telephony"
.SH NAME
siprealm \- show or set authentication realm of sipwitch services
.SH SYNOPSIS
.B siprealm [ 
.I [-md5|-sha1|-rmd160] 
.B ''realm'']
.br
.SH DESCRIPTION
\fBSiprealm\fR is used to either set or display the current authentication
realm of sipwitch services.  This is used to authenticate sip clients.  If
you are aggegating a group of sipwitch servers from multiple hosts, they should
all share the same realm.  If you are running NIS services then it is a
reasonable practice to set the realm of your machines to match your NIS domain.
If you are using a stand-alone sipwitch, such as for an independent desktop
workstation, you might want to use a uuid.  

Only the root user can set the sipwitch domain or hash type.  When either is
changed, any sipwitch digest entries cached are automatically cleared.  This
means that if you have sipwitch setup to generate digests based on user
passwords set through "pam", then you will have to reset or update each user's
password if you change the realm.  For this reason, it's generally advised to
set it only once. 
.SH OPTIONS
.TP
.B -md5
Use md5 digest algorithm (default).
.TP
.B -rmd160
Use rmd160 digest algorithm.
.TP
.B -sha1
Use sha1 digest algorithm.
.SH "EXIT STATUS"
Any error in argument format will return an exit status of 3.  If no realm is
set and used to print the current realm, then an exist status of 1 will be
returned.  The command will normally return with exit status of 0 after 
printing the curret (or new) sip realm.
.SH AUTHOR
.B siprealm
was written by David Sugar <dyfet@gnutelephony.org>.
.SH "REPORTING BUGS"
Report bugs to sipwitch-devel@gnu.org.
.SH COPYRIGHT
Copyright \(co 2010 David Sugar, Tycho Softworks.
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.

