.\" sipwitch - script control and manage GNU sipwitch server.
.\" Copyright (c) 2009 David Sugar <dyfet@gnutelephony.org>
.\"
.\" This manual page is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc.,59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
.\"
.\" This manual page is written especially for Debian GNU/Linux.
.\"
.TH sipwitch "1" "January 2009" "GNU SIP Witch" "GNU Telephony"
.SH NAME
sipwitch \- script control and manage GNU sipwitch server.
.SH SYNOPSIS
.B sipwitch \fIcommand\fR \fI[arguments...]\fR
.br
.SH DESCRIPTION
The sipwitch command allows one to interact with a running sipwitch daemon
instance on the current machine.  This can be used to create management shell
scripts or to perform basic service operations, using the sipwitch fifo control
interface.  Normally this command would be used only by root or someone in an
admin group that the sipwitch deamon is running under.  If the sipwitch deamon
is started by an ordinary user, the command can be used by the same user to
control that daemon instance.
.PP
.TP
\fBabort\fR
terminate running daemon with core for debugging.
.TP
\fBactivate\fR \fIext\fR \fIipaddr\fR
register a static sip extension manually on a fixed address.
.TP
\fBcalls\fR
list active call sessions on the server.
.TP
\fBcheck\fR
verify running daemon for deadlocks or other problems.
.TP
\fBconcurrency\fR \fIlevel\fR
set concurrency level of the daemon.  See pthread_setconcurrency.
.TP
\fBdown\fR
stop and shutdown the running sipwitch daemon.
.TP
\fBdump\fR
dump server configuration to stdout.
.TP
\fBhistory\fR \fI[size]\fR
set size or dump recent error log history.
.TP
\fBmessage\fR \fIext\fR \fI``Text''\fR
send a short text message to a registered extension.
.TP
\fBperiod\fR \fIinterval\fR
dump periodic stats for specified minute interval, often used for cron.
.TP
\fBpstats\fR
dump server periodic statistics.  See ``stats''.
.TP
\fBregistry\fR
dump all user agent registrations to stdout.
.TP
\fBrelease\fR \fIext\fR
deactivate an extension registered with the daemon.
.TP
\fBreload\fR
load server configuration while live.
.TP
\fBrestart\fR
force server restart.
.TP
\fBsnapshot\fR
create snapshot diagnostic file from daemon.
.TP
\fBstate\fR \fIid\fR
set daemon to specified state id.
.TP
\fBstats\fR
dump server call statistics.
.TP
\fBstatus\fR
server mapped call status list.
.TP
\fBtrace\fR \fIon|off|clear\fR
Set or clear server sip message tracing.
.TP
\fBverbose\fR \fIlevel\fR
set daemon error logging verbosity.
.SH "EXIT STATUS"
Normally exit status is 0 if the request was successfully processed by the
sipwitch service daemon.  An exit status of 1 indicates the request timed
out and 2 indicates the server is offline.  If the request failed, then a
3 is returned.  A 255 (\-1) indicates a syntax error in the command request
or arguments. 
.SH AUTHOR
.B sipwitch
was written by David Sugar <dyfet@gnutelephony.org>.
.SH "REPORTING BUGS"
Report bugs to sipwitch-devel@gnu.org.
.SH COPYRIGHT
Copyright \(co 2009 David Sugar, Tycho Softworks.
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE. 

