.\" sipwitch - script control and manage GNU sipwitch server.
.\" Copyright (c) 2009 David Sugar <dyfet@gnutelephony.org>
.\"
.\" This manual page is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc.,59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
.\"
.\" This manual page is written especially for Debian GNU/Linux.
.\"
.TH sipwitch "1" "January 2009" "GNU SIP Witch" "GNU Telephony"
.SH NAME
sipwitch \- script control and manage GNU sipwitch server.
.SH SYNOPSIS
.B sipwitch
.B command
.RI [ arguments... ]
.br
.SH DESCRIPTION
The sipwitch command allows one to interact with a running sipwitch daemon
instance on the current machine.  This can be used to create management shell
scripts or to perform basic service operations, using the sipwitch fifo control
interface.  Normally this command would be used only by root or someone in an
admin group that the sipwitch daemon is running under.  If the sipwitch daemon
is started by an ordinary user, the command can be used by the same user to
control that daemon instance.
.PP
.TP
.B abort
terminate running daemon with core for debugging.
.TP
.BI activate " ext ipaddr"
register a static sip extension manually on a fixed address.
.TP
.B calls
list active call sessions on the server.
.TP
.B check
verify running daemon for deadlocks or other problems.
.TP
.BI concurrency " level"
set concurrency level of the daemon.  See pthread_setconcurrency.
.TP
.BI digest " userid [realm [type]]"
compute a sip digest for the server realm.
.TP
.B down
stop and shutdown the running sipwitch daemon.
.TP
.BI drop " user|callid"
drop specified calls either by a user or call id.
.TP
.B dump
dump server configuration to stdout.
.TP
.B events
display server events as received.
.TP
.BI history " [size]"
set size or dump recent error log history.
.TP
.BI ifdown " iface"
notify server interface went down.
.TP
.BI ifup " iface"
notify server interface came up.
.TP
.BI message " ext ``Text''"
send a short text message to a registered extension.
.TP
.BI period " interval"
dump periodic stats for specified minute interval, often used for cron.
.TP
.B pstats
dump server periodic statistics.  See ``stats''.
.TP
.B registry
dump all user agent registrations to stdout.
.TP
.BI realm " [new-realm [digest-type]]"
set or show the server realm.
.TP
.BI release " ext"
deactivate an extension registered with the daemon.
.TP
.B reload
load server configuration while live.
.TP
\fBrestart\fR
force server restart.
.TP
.B siplog
dump sip messages from when trace is enabled.
.TP
.B snapshot
create snapshot diagnostic file from daemon.
.TP
.BI state " id"
set daemon to specified state id.
.TP
.B stats
dump server call statistics.
.TP
.B status
server mapped call status list.
.TP
.BI trace " on|off|clear"
Set or clear server sip message tracing.
.TP
.B usercache
dump user cache.
.TP
.BI verbose " level"
set daemon error logging verbosity.
.SH "EXIT STATUS"
Normally exit status is 0 if the request was successfully processed by the
sipwitch service daemon.  An exit status of 0x indicates an error in the
sipwitch utility, such as invalid argument parsing.  An error of 1x indicates
some communication failure with the server, and a error of 2x is related to
errors on server processed requests.
.SH AUTHOR
.B sipwitch
was written by David Sugar <dyfet@gnutelephony.org>.
.SH "REPORTING BUGS"
Report bugs to sipwitch-devel@gnu.org.
.SH COPYRIGHT
Copyright \(co 2009 David Sugar, Tycho Softworks.
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.

